---
- name: Ensure logstash home dir is created
  file: 
    path:  "{{ logstash_home_dir }}" 
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode:  0775
    state: directory

- name: Create logstash settings file
  template: 
    src:   logstash.yml.j2
    dest:  "{{ logstash_settings_dir }}/logstash.yml"
    owner: root
    group: root
    mode:  0644
  notify: 
    - Restart logstash

- name: Create logstash jvm.options settings file
  template: 
    src:   jvm.options.j2
    dest:  "{{ logstash_settings_dir }}/jvm.options"
    owner: root
    group: root
    mode:  0644
  notify: 
    - Restart logstash

- name: Create logstash startup.options settings file
  template: 
    src:   startup.options.j2
    dest:  "{{ logstash_settings_dir }}/startup.options"
    owner: root
    group: root
    mode:  0644
  notify: 
    - Restart logstash

- name: Create logstash pipeline input config
  template: 
    src:   input.conf.j2
    dest:  "{{ logstash_conf_dir }}/10-input.conf"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode:  0644
  when: logstash_input_configs
  notify: 
    - Validate logstash config
    - Restart logstash

- name: Create logstash pipeline filter config
  template: 
    src:   filter.conf.j2
    dest:  "{{ logstash_conf_dir }}/20-filter.conf"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode:  0644
  when: logstash_filter_configs
  notify: 
    - Validate logstash config
    - Restart logstash

- name: Create logstash pipeline output config
  template: 
    src:   output.conf.j2
    dest:  "{{ logstash_conf_dir }}/30-output.conf"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode:  0644
  when: logstash_output_configs
  notify: 
    - Validate logstash config
    - Restart logstash

- name: Logstash Plugins
  include: plugins.yml

- name: Start logstash
  service: name=logstash enabled=yes state=started