- name: Setup AWS EC2 instances for Elasticsearch
  hosts: localhost
  gather_facts: false
  connection: local

  roles:
    - aws-elasticsearch

  tasks:
    - name: Provision a set of instances
      add_host: hostname={{ item.public_ip }} groups=ec2_group_elasticsearch
      loop: "{{ ec2_elk_elasticsearch.tagged_instances }}"

    - name: wait for instances
      pause:
       minutes: 1


- name: Setup Elasticsearch
  hosts: ec2_group_elasticsearch
  user: ec2-user
  become: true

  roles:
    - role: elastic.elasticsearch
      es_instance_name: "node1"
      es_host_api: _eth0_
      es_enable_xpack: false