- name: Setup AWS EC2 instances for Logstash
  hosts: localhost
  gather_facts: false
  connection: local

  roles:
    - aws-logstash
  
  tasks:
    - name: Provision a set of instances
      add_host: hostname={{ item.public_ip }} groups=ec2_group_logstash
      loop: "{{ ec2_elk_logstash.tagged_instances }}"

- name: Install and Config Logstash
  hosts: ec2_group_logstash
  user: ec2-user
  become: true

  roles:
    - java
    - service-logstash
