- name: create EC2 instance for Logstash
  ec2:
    image: ami-05868579 # Amazon Linux 2 AMI (HVM)
    key_name: gpu
    wait: yes
    instance_type: t2.micro
    group_id: "{{ sg_ec2_elk_logstash.group_id }}" 
    region: ap-southeast-1
    instance_tags:
      Name: elk-logstash
    volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: 10
    count_tag:
      Name: elk-logstash
    exact_count: 2 
  register: ec2_elk_logstash