- name: Get EC2 instances
  set_fact:
    ec2_targets: "{{ ec2_targets|default([]) + [{'Id': item.id, 'Port': 80 }] }}"
  loop: "{{ ec2_elk_logstash.tagged_instances }}"

- name: target group for ALB
  elb_target_group:
    region: ap-southeast-1
    name: tg-elk-logstash
    protocol: http
    port: 80
    vpc_id: vpc-5bc2ac3e
    health_check_path: /
    successful_response_codes: "200"
    targets: "{{ ec2_targets }}"
    state: present