---
logstash_user:  logstash
logstash_group: "{{ logstash_user }}"

logstash_log_dir:       /var/log/logstash
logstash_settings_dir:  /etc/logstash
logstash_conf_dir:      "{{ logstash_settings_dir }}/conf.d"
logstash_pid_dir:       /var/run

# v5.x
logstash_home_dir:      /usr/share/logstash
logstash_bin_dir:       "{{ logstash_home_dir }}/bin"
logstash_plugins_dir:   "{{ logstash_home_dir }}/plugins"

####################
##  Default Settings
logstash_javacmd: /usr/bin/java
logstash_opts:      []                # e.g. [ "--debug" ]
logstash_java_opts: []
logstash_heap_size: "1g"
logstash_nice:       19
logstash_open_files: 16384
logstash_use_gc_logging: false
logstash_kill_on_stop_timeout: 0
logstash_log_level: info

############
##  Package
logstash_version:            '1:6.2.2-1'
logstash_normalized_version: "{{ logstash_version.split(':')|last + '.str' }}"   # adding '.str' to workaround "'float object' has no attribute 'split'" error
                                                                                 # noticed with Ansible v2.1 if logstash_version is indeed a float e.g. 2.4
logstash_major_version:      "{{ logstash_normalized_version.split('.')|first }}"
logstash_minor_version:      "{{ logstash_normalized_version.split('.')[1] }}"
logstash_repo_version:       "{{ logstash_major_version }}.{{ logstash_minor_version }}"
logstash_signing_key_url:    "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
logstash_apt_repo:           "deb https://artifacts.elastic.co/packages/{{ logstash_major_version }}.x/apt stable main"
logstash_yum_repo_baseurl:   "https://artifacts.elastic.co/packages/{{ logstash_major_version }}.x/yum"

###########
##  Config
logstash_input_configs:
  - |
    file {
            path => ["/var/log/boot.log"]
       }
logstash_filter_configs: []
logstash_output_configs:
  - |
    stdout {
            codec => rubydebug
        }
  - |
    elasticsearch {
            hosts => ["localhost:9200"]
        }
logstash_update_plugins:  false
logstash_plugins_install: []
logstash_plugins_remove:  []

logstash_config_validate_cmd:   "{{ logstash_bin_dir }}/logstash --config.test_and_exit --path.settings /etc/logstash"